# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# ignore all warnings from all pods
  inhibit_all_warnings!

target 'HealthyLivingOptimized' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthyLivingOptimized
        pod 'IQKeyboardManagerSwift'
        pod 'NVActivityIndicatorView'
        pod 'BEMCheckBox'
        pod 'Eureka'
        pod 'SwiftyCam'
        pod 'YPImagePicker'
  # Network
        pod 'Alamofire'
        pod 'Kingfisher'
        pod "PromiseKit/CorePromise", "~> 6.8"
        pod "PromiseKit/Foundation"

        pod 'SwiftyBeaver'
        pod 'KeychainAccess'

  #AWS
        pod 'AWSCore'
        pod 'AWSCognitoIdentityProvider'


end
